# Generated by Django 3.2.8 on 2021-10-26 05:10

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Super user status'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='no name', max_length=150, verbose_name='Username'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
