# Generated by Django 3.2.8 on 2021-10-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211026_0510'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_user',
        ),
    ]
