# Generated by Django 3.2.8 on 2021-10-27 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='rating',
        ),
    ]
